trigger:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: MyFirstPython
      name: PoowadolDev/SimpleFastAPI-Python
      endpoint: MyGitHubServiceConnection
      type: github
      ref: main

pool: Self-Host

jobs:
  - job: Clone
    steps:
      - checkout: MyFirstPython
        displayName: checkout SimpleFast
        continueOnError: false