trigger:
  branches:
    include:
      - main

pool: Self-Host

jobs:
  - job:
    steps:
    - script: git clone --branch main --depth 1 https://github.com/PoowadolDev/SimpleFastAPI-Python.git
      displayName: 'Clone Source Code Repo'

    - script: |
        cd SimpleFastAPI-Python
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
      displayName: 'Install Dependencies'

    - script: |
        cd SimpleFastAPI-Python
        source venv/bin/activate
        pytest
      displayName: 'Run Tests'

    - task: DeleteFiles@1
      displayName: 'Clean Build Directory'
      condition: always()
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: '**/*'
        RemoveSourceFolder: false