trigger:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: simplefastapi-python
      name: SimpleFastAPI
      type: git
      ref: main

pool: Self-Host

jobs:
  - job: Clone
    steps:
      - checkout: SimpleFastAPI-Python
        displayName: checkout SimpleFast
        continueOnError: false