trigger:
  branches:
    include:
      - main

pool: Self-Host

jobs:
  - job:
    steps:
    - task: DeleteFiles@1
      displayName: 'Clean Build Directory'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: '**/*'
        RemoveSourceFolder: false

    - script: git clone --branch main --depth 1 https://github.com/PoowadolDev/SimpleFastAPI-Python.git
      displayName: 'Clone Source Code Repo'

    - task: DeleteFiles@1
      displayName: 'Clean Build Directory'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: '**/*'
        RemoveSourceFolder: false