trigger:
  branches:
    include:
      - main

pool: Self-Host

jobs:
  - job:
    steps:
    - script: git clone --branch main https://github.com/PoowadolDev/SimpleFastAPI-Python.git
    displayName: 'Clone Source Code Repo'